addReviewers: false
addAssignees: true
numberOfReviewers: 0
numberOfAssignees: 1
useReviewGroups: false
useAssigneeGroups: true
assigneeGroups:
  scheduling:
    # Tech Leaders
    - rleungx
    # Committers
    - nolouch
    - disksing
    - lhy1024
    - Yisaer
    - HunDunDM
    - JmPotato
filterLabels:
  # Run
  include:
    - contribution
