language: go

go:
  - 1.10.x

script:
  - make setup ci

matrix:
  include:
  - go: 1.10.x
    install:
      - go get github.com/mattn/goveralls
    env:
      - TRAVIS_COVERAGE=1
    script:
      - make setup ci
    after_success:
      - travis_wait make travis_coverage
