language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
    - $GOPATH/src/github.com/tikv/pd/.tools
    # Cache for old branches
    - $GOPATH/src/github.com/tikv/pd/.retools

go:
  - 1.13

script:
  - make ci

matrix:
  include:
  - go: 1.13
    env:
      - TRAVIS_COVERAGE=1
    script:
      - make ci
