[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.3.4"

[[override]]
  name = "github.com/coreos/bbolt"
  version = "=v1.3.1-coreos.6"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "~1.3"

[[constraint]]
  name = "google.golang.org/grpc"
  source = "https://github.com/grpc/grpc-go.git"
  version = "1.12.0"

[[constraint]]
  name = "github.com/chzyer/readline"
  branch = "master"

[[constraint]]
  name = "github.com/pingcap/kvproto"
  branch = "master"
