# PD Simulator Configuration

[tick]
# the tick interval when starting PD inside (default: "100ms")
sim-tick-interval = "100ms"
# the tick interval when connecting with an external PD (default: "1s")
norm-tick-interval = "1s"

[store]
# the capacity size of a new store in GB (default: 1024)
store-capacity = 1024
# the available size of a new store in GB (default: 1024)
store-available = 1024
# the io rate of a new store in MB/s (default: 40)
store-io-per-second = 40
# the version of a new store (default: "2.1.0")
store-version = "2.1.0"
