basePath: /pd/api/v1
definitions:
  api.version:
    properties:
      version:
        type: string
    type: object
host: http://localhost:2379
info:
  contact:
    email: info@pingcap.com
    name: Placement Driver Support
    url: https://github.com/pingcap/pd/issues
  description: This is placement driver.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://pingcap.com
  title: PingCAP Placement Driver API
  version: "1.0"
paths:
  /version:
    get:
      description: Get the version of PD server
      operationId: get-version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.version'
      summary: Get the version of PD server
swagger: "2.0"
